# Generated by Django 4.1.7 on 2023-03-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('state_abbr', models.CharField(max_length=10)),
                ('median_home_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conventional_one_unit', models.IntegerField()),
                ('conventional_two_unit', models.IntegerField()),
                ('conventional_three_unit', models.IntegerField()),
                ('conventional_four_unit', models.IntegerField()),
                ('fha_one_unit', models.IntegerField()),
                ('fha_two_unit', models.IntegerField()),
                ('fha_three_unit', models.IntegerField()),
                ('fha_four_unit', models.IntegerField()),
                ('conventional_effective_date', models.DateField(default='2023-01-01')),
                ('fha_effective_date', models.DateField(default='2023-01-01')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage_backend.county')),
            ],
        ),
    ]
