# Generated by Django 4.1.7 on 2023-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('state_abbr', models.CharField(max_length=10)),
                ('median_home_value', models.IntegerField()),
            ],
        ),
    ]
