# Generated by Django 4.1.7 on 2023-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_Limit',
            new_name='LoanLimit',
        ),
    ]
