# Generated by Django 4.1.7 on 2023-03-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='median_home_value',
        ),
    ]
