# Generated by Django 4.1.7 on 2023-03-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0002_rename_loan_limit_loanlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHALoanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_unit', models.IntegerField()),
                ('two_unit', models.IntegerField()),
                ('three_unit', models.IntegerField()),
                ('four_unit', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage_backend.county')),
            ],
        ),
        migrations.CreateModel(
            name='ConventionalLoanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_unit', models.IntegerField()),
                ('two_unit', models.IntegerField()),
                ('three_unit', models.IntegerField()),
                ('four_unit', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage_backend.county')),
            ],
        ),
    ]
