# Generated by Django 4.1.7 on 2023-03-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0002_remove_county_median_home_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='name',
            new_name='county_name',
        ),
        migrations.AddField(
            model_name='county',
            name='median_home_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
