# Generated by Django 4.1.7 on 2023-03-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0003_fhaloanlimit_conventionalloanlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionalloanlimit',
            name='county',
        ),
        migrations.RemoveField(
            model_name='fhaloanlimit',
            name='county',
        ),
    ]
