# Generated by Django 4.1.7 on 2023-03-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0004_remove_conventionalloanlimit_county_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConventionalLoanLimit',
        ),
        migrations.DeleteModel(
            name='FHALoanLimit',
        ),
    ]
