# Generated by Django 4.1.7 on 2023-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0005_delete_conventionalloanlimit_delete_fhaloanlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLimitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=20)),
                ('one_unit', models.IntegerField()),
                ('two_unit', models.IntegerField()),
                ('three_unit', models.IntegerField()),
                ('four_unit', models.IntegerField()),
                ('effective_date', models.DateField(default='2023-01-01')),
            ],
        ),
    ]
