# Generated by Django 4.1.7 on 2023-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0008_loanlimit_conventional_loan_limits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanlimit',
            name='conventional_loan_limits',
        ),
        migrations.RemoveField(
            model_name='loanlimit',
            name='fha_loan_limits',
        ),
        migrations.AddField(
            model_name='county',
            name='conventional_loan_limits',
            field=models.ManyToManyField(related_name='conventional_loan_limits', to='mortgage_backend.loanlimitoption'),
        ),
        migrations.AddField(
            model_name='county',
            name='fha_loan_limits',
            field=models.ManyToManyField(related_name='fha_loan_limits', to='mortgage_backend.loanlimitoption'),
        ),
    ]
