# Generated by Django 4.1.7 on 2023-03-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0009_remove_loanlimit_conventional_loan_limits_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanLimit',
        ),
    ]
