# Generated by Django 4.2 on 2023-05-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_backend', '0010_delete_loanlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='median_home_value',
        ),
    ]
